// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmlmPfI23K9LQ2_EtG3s3e4KgCd-32Dg',
    appId: '1:11681464566:web:f2dc0a12697e9da7f2ecd7',
    messagingSenderId: '11681464566',
    projectId: 'towpal-9eb27',
    authDomain: 'towpal-9eb27.firebaseapp.com',
    databaseURL: 'https://towpal-9eb27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'towpal-9eb27.appspot.com',
    measurementId: 'G-DN92K7R1TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQplWO-bGid7t6BzZo-wJnfKyPgebZVRk',
    appId: '1:11681464566:android:e8c98f9197b11f47f2ecd7',
    messagingSenderId: '11681464566',
    projectId: 'towpal-9eb27',
    databaseURL: 'https://towpal-9eb27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'towpal-9eb27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE1WOzWhVrHVoeSAFZmihV7B4n7NAF5Nk',
    appId: '1:11681464566:ios:2a035bee544c8cb1f2ecd7',
    messagingSenderId: '11681464566',
    projectId: 'towpal-9eb27',
    databaseURL: 'https://towpal-9eb27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'towpal-9eb27.appspot.com',
    iosBundleId: 'com.example.carihio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE1WOzWhVrHVoeSAFZmihV7B4n7NAF5Nk',
    appId: '1:11681464566:ios:2a035bee544c8cb1f2ecd7',
    messagingSenderId: '11681464566',
    projectId: 'towpal-9eb27',
    databaseURL: 'https://towpal-9eb27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'towpal-9eb27.appspot.com',
    iosBundleId: 'com.example.carihio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHmlmPfI23K9LQ2_EtG3s3e4KgCd-32Dg',
    appId: '1:11681464566:web:f2dc0a12697e9da7f2ecd7',
    messagingSenderId: '11681464566',
    projectId: 'towpal-9eb27',
    authDomain: 'towpal-9eb27.firebaseapp.com',
    databaseURL: 'https://towpal-9eb27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'towpal-9eb27.appspot.com',
    measurementId: 'G-DN92K7R1TV',
  );

}